# Generated by Django 4.2.7 on 2026-01-01 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('about', 'About Us'), ('life', 'Life at Company'), ('benefits', 'Benefits'), ('values', 'Values'), ('mission', 'Mission'), ('custom', 'Custom')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_sections', to='companies.company')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('company', 'order')},
            },
        ),
    ]
